Chore: e2e tests on matching component (Issue/181)
adaptlearning/adapt-contrib-matching pull request #182
Opened 2024-03-26 19:43 UTC by lemmyadams

Addresses #181

2024-03-27 11:01 UTC, lemmyadams commented
Relies on https://github.com/adaptlearning/adapt_framework/pull/3533

2024-03-28 09:52 UTC, cahirodoherty-learningpool approved these changes
👀

2024-03-28 12:23 UTC, ethan-lp approved these changes

2024-04-08 11:50 UTC, oliverfoster requested changes

2024-04-08 11:50 UTC, oliverfoster commented on test/e2e/matching.cy.js
> +      cy.testContainsOrNotExists('.matching__instruction', matchingComponent.instruction)
```suggestion
      const stripHtml = cy.helpers.stripHtml;
      cy.testContainsOrNotExists('.matching__body', stripHtml(bodyWithoutHtml))
      cy.testContainsOrNotExists('.matching__title', stripHtml(matchingComponent.displayTitle))
      cy.testContainsOrNotExists('.matching__instruction', stripHtml(matchingComponent.instruction))
```

2024-04-08 11:50 UTC, oliverfoster commented on test/e2e/matching.cy.js
> +    matchingComponents.forEach((matchingComponent) => {
```suggestion
    matchingComponents.forEach(matchingComponent => {
```

These brackets aren't needed, please remove them from fat-arrow functions.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#syntax

2024-04-11 13:39 UTC, oliverfoster approved these changes

2024-04-11 13:40 UTC, merged